import { SelectListItem } from './models/select-list';

export class CommonHelper {
  static szobak: SelectListItem[] = [
    { label: 'C01', value: 'C01' },
    { label: 'C06', value: 'C06' },
    { label: 'C07', value: 'C07' },
    { label: 'C08', value: 'C08' },
    { label: 'C09', value: 'C09' },
    { label: 'C10', value: 'C10' },
    { label: 'C11', value: 'C11' },
    { label: 'C12', value: 'C12' },
    { label: 'C13', value: 'C13' },
    { label: 'C14', value: 'C14' },
    { label: 'C17', value: 'C17' },
    { label: 'C18', value: 'C18' },
    { label: 'C19', value: 'C19' },
    { label: 'C20', value: 'C20' },
    { label: 'C21', value: 'C21' },
    { label: 'C22', value: 'C22' },
    { label: 'C24', value: 'C24' },
    { label: 'C25', value: 'C25' },
    { label: 'C28', value: 'C28' },
    { label: 'C31', value: 'C31' },
    { label: 'C34', value: 'C34' },
    { label: 'C35', value: 'C35' },
    { label: 'C36', value: 'C36' },
    { label: 'C37', value: 'C37' },
    { label: 'C38', value: 'C38' },
    { label: 'C39', value: 'C39' },
    { label: 'C40', value: 'C40' },
    { label: 'C41', value: 'C41' },
    { label: 'C42', value: 'C42' },
    { label: 'C43', value: 'C43' },
    { label: 'C48', value: 'C48' },
    { label: 'C49', value: 'C49' },
    { label: 'C50', value: 'C50' },
    { label: 'Enterprise', value: 'Enterprise' },
    { label: 'Discovery', value: 'Discovery' },
    { label: 'Atlantis', value: 'Atlantis' },
    { label: 'Dragon', value: 'Dragon' },
    { label: 'Masat', value: 'Masat' },
    { label: 'Tardis', value: 'Tardis' },
    { label: 'Falcon', value: 'Falcon' },
    { label: 'Voyager1', value: 'Voyager1' },
    { label: 'Voyager2', value: 'Voyager2' },
    { label: 'WC (AB)', value: 'WC (AB)' },
    { label: 'WC (CD)', value: 'WC (CD)' },
    { label: 'WC (EF)', value: 'WC (EF)' }
  ];
}
